# Generated by Django 6.0.7 on 2026-07-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_customuser_address_remove_customuser_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
