# Generated by Django 6.0.7 on 2026-07-17 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_photo_alter_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='personal_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
