services:
 db:
   image: postgres:15
   environment:
     POSTGRES_DB: ${POSTGRES_DB}
     POSTGRES_USER: ${POSTGRES_USER}
     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
   ports:
     - "5432:5432"
   volumes:
     - postgres_data:/var/lib/postgresql/data
   env_file:
     - ../.env

 django-web:
   build: .
   container_name: django-docker
   ports:
     - "8000:8000"
   depends_on:
     - db
   environment:
     DJANGO_SECRET_KEY: ${SECRET_KEY}
     DEBUG: ${DEBUG}
     DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
     DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
     DATABASE_ENGINE: ${DATABASE_ENGINE}
     DATABASE_NAME: ${POSTGRES_DB}
     DATABASE_USERNAME: ${POSTGRES_USER}

     DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
     DATABASE_HOST: ${DB_HOST}
     DATABASE_PORT: ${DB_PORT}
   env_file:
     - ../.env
volumes:
   postgres_data: