# Generated by Django 6.0.7 on 2026-07-21 06:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('seen', 'Seen')], default='new', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('is_system', models.BooleanField(default=False, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('gps_lat', models.FloatField()),
                ('gps_long', models.FloatField()),
                ('location', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('delayed', 'Delayed'), ('in_progress', 'In Progress'), ('done', 'Done')], default='new', max_length=20)),
                ('is_validated', models.BooleanField(default=False)),
                ('validation_status', models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('rejected_duplicate', 'Rejected Duplicate'), ('changes_requested', 'Changes Requested')], default='pending', max_length=30)),
                ('validation_message', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('infrastructure', 'Infrastructure'), ('hazard', 'Hazard'), ('others', 'Others')], default='others', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('report_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='IssueFollower',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='IssueReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AlertRecipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('new', 'New'), ('seen', 'Seen')], default='new', max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_states', to='issue.alert')),
            ],
        ),
    ]
