# Generated by Django 6.0.7 on 2026-07-22 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_initial'),
        ('zone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='zone.zone'),
        ),
    ]
