# Generated by Django 6.0.7 on 2026-07-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0002_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='validation_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='issue',
            name='validation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('rejected_duplicate', 'Rejected Duplicate'), ('changes_requested', 'Changes Requested')], default='pending', max_length=30),
        ),
    ]
