# Generated by Django 6.0.7 on 2026-07-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0004_issue_report_count_comment_issuereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='category',
            field=models.CharField(choices=[('infrastructure', 'Infrastructure'), ('hazard', 'Hazard'), ('others', 'Others')], default='others', max_length=20),
        ),
    ]
