# Generated by Django 6.0.7 on 2026-07-17 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0005_issue_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='is_system',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
