# Generated by Django 6.0.7 on 2026-07-20 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0007_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='is_private',
        ),
        migrations.AlterField(
            model_name='issue',
            name='report_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
