# Generated by Django 6.0.7 on 2026-07-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0008_remove_issue_is_private_alter_issue_report_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='attachments',
        ),
        migrations.AddField(
            model_name='comment',
            name='attachments',
            field=models.ManyToManyField(blank=True, to='issue.attachment'),
        ),
    ]
