# Generated by Django 6.0.7 on 2026-07-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0009_remove_comment_attachments_comment_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
