# Generated by Django 6.0.7 on 2026-07-15 10:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('neighborhood', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('agent_ids', models.CharField(max_length=1000)),
            ],
        ),
    ]
