# Generated by Django 6.0.7 on 2026-07-21 06:22

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('neighborhood', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('agents', models.ManyToManyField(blank=True, limit_choices_to={'role': 'agent'}, related_name='zones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
