# Generated by Django 6.0.7 on 2026-07-20 10:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zone', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='agent_ids',
        ),
        migrations.AddField(
            model_name='zone',
            name='agents',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'agent'}, related_name='zones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
